var App = angular.module('Cabinet', [
  'configuraion',
  'ui.router',
  'ngSanitize',
  'ui.bootstrap', 
  'cabinet.templates',
  'S_eventer', 
  'S_selfapi',
  'S_vk',
  'S_utils',
  'S_location',
  'complexGroupChart',
  'extendedWallPost',
  'ngEnter',
  'vkEmoji',
  'datePickers',
  'parseVkUrls',
  'C_main',
  'C_cabinet', 
  'CCV_index',
  'CCV_groups',
  'CCV_admin_groups.page',
  'CCV_search',
  'CCV_groups.page'
]);
  