<script type="text/javascript" src="/pack/site-vendor.js"></script>
<script type="text/javascript" src="/pack/site-templates.js"></script>
<script type="text/javascript" src="/pack/site-scripts.js"></script>
<?php
if ($_SERVER['HTTP_HOST'] === 'overwatch.ws'){
	echo '<script type="text/javascript">/* PLUSO */ ;(function() {if (window.pluso) if (typeof window.pluso.start == "function") return; if (window.ifpluso == undefined) {window.ifpluso = 1; var d = document, s = d.createElement(\'script\'), g = \'getElementsByTagName\'; s.type = \'text/javascript\'; s.charset = \'UTF-8\'; s.async = true; s.src = (\'https:\' == window.location.protocol ? \'https\' : \'http\') + \'://share.pluso.ru/pluso-like.js\'; var h = d[g](\'body\')[0]; h.appendChild(s); } })(); /* GA */ ;(function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o), m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m) })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\'); ga(\'create\', \'UA-36344603-6\', \'auto\'); ga(\'send\', \'pageview\');/* YA */(function (d, w, c) { (w[c] = w[c] || []).push(function() { try { w.yaCounter27030531 = new Ya.Metrika({id:27030531, clickmap:true, trackLinks:true, accurateTrackBounce:true}); } catch(e) { } }); var n = d.getElementsByTagName("script")[0], s = d.createElement("script"), f = function () { n.parentNode.insertBefore(s, n); }; s.type = "text/javascript"; s.async = true; s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js"; if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); } })(document, window, "yandex_metrika_callbacks");</script><noscript><div><img src="//mc.yandex.ru/watch/27030531" style="position:absolute; left:-9999px;" alt="" /></div></noscript>';
}
?>
</body>
</html>